生成启动时间为 2016/5/13 10:45:10。
     1>项目“D:\sdk Source\xmlconfigure\googletest\msvc\gtest_unittest.vcxproj”在节点 3 上(Build 个目标)。
     1>Link:
         C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\link.exe /ERRORREPORT:PROMPT /OUT:"xmlconfigure/Debug\gtest_unittest.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"xmlconfigure/Debug\gtest_unittest.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"xmlconfigure/Debug\gtest_unittest.lib" /MACHINE:X86 /SAFESEH xmlconfigure/Debug\gtest_unittest\gtest_unittest.obj
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "bool __cdecl testing::internal::IsTrue(bool)" (?IsTrue@internal@testing@@YA_N_N@Z)，该符号在函数 "class testing::internal::ValuesInIteratorRangeGenerator<int>::Iterator const * __cdecl testing::internal::CheckedDowncastToActualType<class testing::internal::ValuesInIteratorRangeGenerator<int>::Iterator const ,class testing::internal::ParamIteratorInterface<int> const >(class testing::internal::ParamIteratorInterface<int> const *)" (??$CheckedDowncastToActualType@$$CBVIterator@?$ValuesInIteratorRangeGenerator@H@internal@testing@@$$CBV?$ParamIteratorInterface@H@34@@internal@testing@@YAPBVIterator@?$ValuesInIteratorRangeGenerator@H@01@PBV?$ParamIteratorInterface@H@01@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall testing::internal::RE::~RE(void)" (??1RE@internal@testing@@QAE@XZ)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::ContainerUtilityDeathTest_ShuffleRange_Test::TestBody(void)" (?TestBody@ContainerUtilityDeathTest_ShuffleRange_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "private: void __thiscall testing::internal::RE::Init(char const *)" (?Init@RE@internal@testing@@AAEXPBD@Z)，该符号在函数 "public: __thiscall testing::internal::RE::RE(char const *)" (??0RE@internal@testing@@QAE@PBD@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl testing::internal::FormatFileLocation(char const *,int)" (?FormatFileLocation@internal@testing@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PBDH@Z)，该符号在函数 "public: bool __thiscall testing::internal::TypedTestCasePState::AddTestName(char const *,int,char const *,char const *)" (?AddTestName@TypedTestCasePState@internal@testing@@QAE_NPBDH00@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall testing::internal::GTestLog::GTestLog(enum testing::internal::GTestLogSeverity,char const *,int)" (??0GTestLog@internal@testing@@QAE@W4GTestLogSeverity@12@PBDH@Z)，该符号在函数 "class testing::internal::ValuesInIteratorRangeGenerator<int>::Iterator const * __cdecl testing::internal::CheckedDowncastToActualType<class testing::internal::ValuesInIteratorRangeGenerator<int>::Iterator const ,class testing::internal::ParamIteratorInterface<int> const >(class testing::internal::ParamIteratorInterface<int> const *)" (??$CheckedDowncastToActualType@$$CBVIterator@?$ValuesInIteratorRangeGenerator@H@internal@testing@@$$CBV?$ParamIteratorInterface@H@34@@internal@testing@@YAPBVIterator@?$ValuesInIteratorRangeGenerator@H@01@PBV?$ParamIteratorInterface@H@01@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall testing::internal::GTestLog::~GTestLog(void)" (??1GTestLog@internal@testing@@QAE@XZ)，该符号在函数 "class testing::internal::ValuesInIteratorRangeGenerator<int>::Iterator const * __cdecl testing::internal::CheckedDowncastToActualType<class testing::internal::ValuesInIteratorRangeGenerator<int>::Iterator const ,class testing::internal::ParamIteratorInterface<int> const >(class testing::internal::ParamIteratorInterface<int> const *)" (??$CheckedDowncastToActualType@$$CBVIterator@?$ValuesInIteratorRangeGenerator@H@internal@testing@@$$CBV?$ParamIteratorInterface@H@34@@internal@testing@@YAPBVIterator@?$ValuesInIteratorRangeGenerator@H@01@PBV?$ParamIteratorInterface@H@01@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "void __cdecl testing::internal::CaptureStdout(void)" (?CaptureStdout@internal@testing@@YAXXZ)，该符号在函数 "protected: static void __cdecl testing::InitGoogleTestTest::TestParsingFlags<char>(int,char const * *,int,char const * *,struct testing::Flags const &,bool)" (??$TestParsingFlags@D@InitGoogleTestTest@testing@@KAXHPAPBDH0ABUFlags@1@_N@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl testing::internal::GetCapturedStdout(void)" (?GetCapturedStdout@internal@testing@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)，该符号在函数 "protected: static void __cdecl testing::InitGoogleTestTest::TestParsingFlags<char>(int,char const * *,int,char const * *,struct testing::Flags const &,bool)" (??$TestParsingFlags@D@InitGoogleTestTest@testing@@KAXHPAPBDH0ABUFlags@1@_N@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl testing::internal::TempDir(void)" (?TempDir@internal@testing@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)，该符号在函数 "public: virtual void __thiscall testing::FlagfileTest::SetUp(void)" (?SetUp@FlagfileTest@testing@@UAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: void __thiscall testing::internal::Mutex::Lock(void)" (?Lock@Mutex@internal@testing@@QAEXXZ)，该符号在函数 "public: __thiscall testing::internal::GTestMutexLock::GTestMutexLock(class testing::internal::Mutex *)" (??0GTestMutexLock@internal@testing@@QAE@PAVMutex@12@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: void __thiscall testing::internal::Mutex::Unlock(void)" (?Unlock@Mutex@internal@testing@@QAEXXZ)，该符号在函数 "public: __thiscall testing::internal::GTestMutexLock::~GTestMutexLock(void)" (??1GTestMutexLock@internal@testing@@QAE@XZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: void __thiscall testing::internal::ThreadWithParamBase::Join(void)" (?Join@ThreadWithParamBase@internal@testing@@QAEXXZ)，该符号在函数 "protected: static void __cdecl `anonymous namespace'::ScopedFakeTestPartResultReporterWithThreadsTest::AddFailureInOtherThread(enum A0x1795f68d::ScopedFakeTestPartResultReporterTest::FailureMode)" (?AddFailureInOtherThread@ScopedFakeTestPartResultReporterWithThreadsTest@?A0x1795f68d@@KAXW4FailureMode@ScopedFakeTestPartResultReporterTest@2@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "protected: __thiscall testing::internal::ThreadWithParamBase::ThreadWithParamBase(class testing::internal::ThreadWithParamBase::Runnable *,class testing::internal::Notification *)" (??0ThreadWithParamBase@internal@testing@@IAE@PAVRunnable@012@PAVNotification@12@@Z)，该符号在函数 "public: __thiscall testing::internal::ThreadWithParam<enum `anonymous namespace'::ScopedFakeTestPartResultReporterTest::FailureMode>::ThreadWithParam<enum `anonymous namespace'::ScopedFakeTestPartResultReporterTest::FailureMode>(void (__cdecl*)(enum `anonymous namespace'::ScopedFakeTestPartResultReporterTest::FailureMode),enum `anonymous namespace'::ScopedFakeTestPartResultReporterTest::FailureMode,class testing::internal::Notification *)" (??0?$ThreadWithParam@W4FailureMode@ScopedFakeTestPartResultReporterTest@?A0x1795f68d@@@internal@testing@@QAE@P6AXW4FailureMode@ScopedFakeTestPartResultReporterTest@?A0x1795f68d@@@Z0PAVNotification@12@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "protected: virtual __thiscall testing::internal::ThreadWithParamBase::~ThreadWithParamBase(void)" (??1ThreadWithParamBase@internal@testing@@MAE@XZ)，该符号在函数 "public: virtual __thiscall testing::internal::ThreadWithParam<enum `anonymous namespace'::ScopedFakeTestPartResultReporterTest::FailureMode>::~ThreadWithParam<enum `anonymous namespace'::ScopedFakeTestPartResultReporterTest::FailureMode>(void)" (??1?$ThreadWithParam@W4FailureMode@ScopedFakeTestPartResultReporterTest@?A0x1795f68d@@@internal@testing@@UAE@XZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "int __cdecl testing::internal::Int32FromGTestEnv(char const *,int)" (?Int32FromGTestEnv@internal@testing@@YAHPBDH@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::Int32FromGTestEnvTest_ParsesAndReturnsValidValue_Test::TestBody(void)" (?TestBody@Int32FromGTestEnvTest_ParsesAndReturnsValidValue_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall testing::Message::Message(void)" (??0Message@testing@@QAE@XZ)，该符号在函数 "public: class testing::AssertionResult & __thiscall testing::AssertionResult::operator<<<char const [2]>(char const (&)[2])" (??$?6$$BY01$$CBD@AssertionResult@testing@@QAEAAV01@AAY01$$CBD@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: class testing::Message & __thiscall testing::Message::operator<<(wchar_t const *)" (??6Message@testing@@QAEAAV01@PB_W@Z)，该符号在函数 "public: static void __cdecl `private: virtual void __thiscall `anonymous namespace'::AssertionWithMessageTest_WideStringMessage_Test::TestBody(void)'::`15'::GTestExpectFatalFailureHelper::Execute(void)" (?Execute@GTestExpectFatalFailureHelper@?P@??TestBody@AssertionWithMessageTest_WideStringMessage_Test@?A0x1795f68d@@EAEXXZ@SAXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: class testing::Message & __thiscall testing::Message::operator<<(wchar_t *)" (??6Message@testing@@QAEAAV01@PA_W@Z)，该符号在函数 "private: virtual void __thiscall MessageTest_WideStrings_Test::TestBody(void)" (?TestBody@MessageTest_WideStrings_Test@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall testing::Message::GetString(void)const " (?GetString@Message@testing@@QBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)，该符号在函数 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl testing::internal::DefaultParamName<int>(struct testing::TestParamInfo<int> const &)" (??$DefaultParamName@H@internal@testing@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABU?$TestParamInfo@H@1@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl testing::internal::String::ShowWideCString(wchar_t const *)" (?ShowWideCString@String@internal@testing@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PB_W@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::StringTest_ShowWideCString_Test::TestBody(void)" (?TestBody@StringTest_ShowWideCString_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: static bool __cdecl testing::internal::String::CaseInsensitiveWideCStringEquals(wchar_t const *,wchar_t const *)" (?CaseInsensitiveWideCStringEquals@String@internal@testing@@SA_NPB_W0@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::StringTest_CaseInsensitiveWideCStringEquals_Test::TestBody(void)" (?TestBody@StringTest_CaseInsensitiveWideCStringEquals_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: static bool __cdecl testing::internal::String::EndsWithCaseInsensitive(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?EndsWithCaseInsensitive@String@internal@testing@@SA_NABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::StringTest_EndsWithCaseInsensitive_Test::TestBody(void)" (?TestBody@StringTest_EndsWithCaseInsensitive_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl testing::internal::StringStreamToString(class std::basic_stringstream<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?StringStreamToString@internal@testing@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PAV?$basic_stringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z)，该符号在函数 "class testing::AssertionResult __cdecl testing::internal::CmpHelperFloatingPointEQ<float>(char const *,char const *,float,float)" (??$CmpHelperFloatingPointEQ@M@internal@testing@@YA?AVAssertionResult@1@PBD0MM@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: static class testing::internal::FilePath __cdecl testing::internal::FilePath::GenerateUniqueFileName(class testing::internal::FilePath const &,class testing::internal::FilePath const &,char const *)" (?GenerateUniqueFileName@FilePath@internal@testing@@SA?AV123@ABV123@0PBD@Z)，该符号在函数 "public: class testing::internal::FilePath __thiscall testing::FlagfileTest::CreateFlagfile(char const *)" (?CreateFlagfile@FlagfileTest@testing@@QAE?AVFilePath@internal@2@PBD@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: bool __thiscall testing::internal::FilePath::CreateFolder(void)const " (?CreateFolder@FilePath@internal@testing@@QBE_NXZ)，该符号在函数 "public: virtual void __thiscall testing::FlagfileTest::SetUp(void)" (?SetUp@FlagfileTest@testing@@UAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "private: void __thiscall testing::internal::FilePath::Normalize(void)" (?Normalize@FilePath@internal@testing@@AAEXXZ)，该符号在函数 "public: __thiscall testing::internal::FilePath::FilePath(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0FilePath@internal@testing@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl testing::internal::AppendUserMessage(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class testing::Message const &)" (?AppendUserMessage@internal@testing@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV34@ABVMessage@2@@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::AssertionTest_AppendUserMessage_Test::TestBody(void)" (?TestBody@AssertionTest_AppendUserMessage_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class std::vector<enum testing::internal::edit_distance::EditType,class std::allocator<enum testing::internal::edit_distance::EditType> > __cdecl testing::internal::edit_distance::CalculateOptimalEdits(class std::vector<unsigned int,class std::allocator<unsigned int> > const &,class std::vector<unsigned int,class std::allocator<unsigned int> > const &)" (?CalculateOptimalEdits@edit_distance@internal@testing@@YA?AV?$vector@W4EditType@edit_distance@internal@testing@@V?$allocator@W4EditType@edit_distance@internal@testing@@@std@@@std@@ABV?$vector@IV?$allocator@I@std@@@5@0@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::EditDistance_TestCases_Test::TestBody(void)" (?TestBody@EditDistance_TestCases_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl testing::internal::edit_distance::CreateUnifiedDiff(class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &,unsigned int)" (?CreateUnifiedDiff@edit_distance@internal@testing@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@5@0I@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::EditDistance_TestCases_Test::TestBody(void)" (?TestBody@EditDistance_TestCases_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::internal::EqFailure(char const *,char const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool)" (?EqFailure@internal@testing@@YA?AVAssertionResult@2@PBD0ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1_N@Z)，该符号在函数 "class testing::AssertionResult __cdecl testing::internal::CmpHelperEQFailure<char const [1],class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(char const *,char const *,char const (&)[1],class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??$CmpHelperEQFailure@$$BY00$$CBDV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@internal@testing@@YA?AVAssertionResult@1@PBD0AAY00$$CBDABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl testing::internal::GetBoolAssertionFailureMessage(class testing::AssertionResult const &,char const *,char const *,char const *)" (?GetBoolAssertionFailureMessage@internal@testing@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABVAssertionResult@2@PBD11@Z)，该符号在函数 "public: static void __cdecl `void __cdecl `anonymous namespace'::DoesNotAbortHelper(bool *)'::`4'::GTestExpectFatalFailureHelper::Execute(void)" (?Execute@GTestExpectFatalFailureHelper@?3??DoesNotAbortHelper@?A0x1795f68d@@YAXPA_N@Z@SAXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "void const * __cdecl testing::internal::GetTestTypeId(void)" (?GetTestTypeId@internal@testing@@YAPBXXZ)，该符号在函数 "void __cdecl `dynamic initializer for 'private: static class testing::TestInfo * AddReferenceTest_AddsReference_Test::test_info_''(void)" (??__E?test_info_@AddReferenceTest_AddsReference_Test@@0QAVTestInfo@testing@@A@@YAXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::internal::IsHRESULTSuccess(char const *,long)" (?IsHRESULTSuccess@internal@testing@@YA?AVAssertionResult@2@PBDJ@Z)，该符号在函数 "public: static void __cdecl `private: virtual void __thiscall `anonymous namespace'::HRESULTAssertionTest_Streaming_Test::TestBody(void)'::`30'::GTestExpectFatalFailureHelper::Execute(void)" (?Execute@GTestExpectFatalFailureHelper@?BO@??TestBody@HRESULTAssertionTest_Streaming_Test@?A0x1795f68d@@EAEXXZ@SAXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::internal::IsHRESULTFailure(char const *,long)" (?IsHRESULTFailure@internal@testing@@YA?AVAssertionResult@2@PBDJ@Z)，该符号在函数 "public: static void __cdecl `private: virtual void __thiscall `anonymous namespace'::HRESULTAssertionTest_ASSERT_HRESULT_FAILED_Test::TestBody(void)'::`8'::GTestExpectFatalFailureHelper::Execute(void)" (?Execute@GTestExpectFatalFailureHelper@?7??TestBody@HRESULTAssertionTest_ASSERT_HRESULT_FAILED_Test@?A0x1795f68d@@EAEXXZ@SAXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::TestInfo * __cdecl testing::internal::MakeAndRegisterTestInfo(char const *,char const *,char const *,char const *,struct testing::internal::CodeLocation,void const *,void (__cdecl*)(void),void (__cdecl*)(void),class testing::internal::TestFactoryBase *)" (?MakeAndRegisterTestInfo@internal@testing@@YAPAVTestInfo@2@PBD000UCodeLocation@12@PBXP6AXXZ3PAVTestFactoryBase@12@@Z)，该符号在函数 "void __cdecl `dynamic initializer for 'private: static class testing::TestInfo * AddReferenceTest_AddsReference_Test::test_info_''(void)" (??__E?test_info_@AddReferenceTest_AddsReference_Test@@0QAVTestInfo@testing@@A@@YAXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "bool __cdecl testing::internal::SkipPrefix(char const *,char const * *)" (?SkipPrefix@internal@testing@@YA_NPBDPAPBD@Z)，该符号在函数 "private: virtual void __thiscall SkipPrefixTest_DoesNotSkipWhenPrefixDoesNotMatch_Test::TestBody(void)" (?TestBody@SkipPrefixTest_DoesNotSkipWhenPrefixDoesNotMatch_Test@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: char const * __thiscall testing::internal::TypedTestCasePState::VerifyRegisteredTestNames(char const *,int,char const *)" (?VerifyRegisteredTestNames@TypedTestCasePState@internal@testing@@QAEPBDPBDH0@Z)，该符号在函数 "void __cdecl testing::`dynamic initializer for 'gtest_registered_test_names_CodeLocationForTYPEDTESTP_''(void)" (??__Egtest_registered_test_names_CodeLocationForTYPEDTESTP_@testing@@YAXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl testing::internal::GetCurrentOsStackTraceExceptTop(class testing::UnitTest *,int)" (?GetCurrentOsStackTraceExceptTop@internal@testing@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PAVUnitTest@2@H@Z)，该符号在函数 "private: virtual void __thiscall GetCurrentOsStackTraceExceptTopTest_ReturnsTheStackTrace_Test::TestBody(void)" (?TestBody@GetCurrentOsStackTraceExceptTopTest_ReturnsTheStackTrace_Test@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "bool __cdecl testing::internal::AlwaysTrue(void)" (?AlwaysTrue@internal@testing@@YA_NXZ)，该符号在函数 "bool __cdecl testing::internal::AlwaysFalse(void)" (?AlwaysFalse@internal@testing@@YA_NXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: unsigned int __thiscall testing::internal::Random::Generate(unsigned int)" (?Generate@Random@internal@testing@@QAEII@Z)，该符号在函数 "void __cdecl testing::internal::ShuffleRange<int>(class testing::internal::Random *,int,int,class std::vector<int,class std::allocator<int> > *)" (??$ShuffleRange@H@internal@testing@@YAXPAVRandom@01@HHPAV?$vector@HV?$allocator@H@std@@@std@@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: static bool __cdecl testing::internal::DeathTest::Create(char const *,class testing::internal::RE const *,char const *,int,class testing::internal::DeathTest * *)" (?Create@DeathTest@internal@testing@@SA_NPBDPBVRE@23@0HPAPAV123@@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::ContainerUtilityDeathTest_ShuffleRange_Test::TestBody(void)" (?TestBody@ContainerUtilityDeathTest_ShuffleRange_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: static char const * __cdecl testing::internal::DeathTest::LastMessage(void)" (?LastMessage@DeathTest@internal@testing@@SAPBDXZ)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::ContainerUtilityDeathTest_ShuffleRange_Test::TestBody(void)" (?TestBody@ContainerUtilityDeathTest_ShuffleRange_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "bool __cdecl testing::internal::ExitedUnsuccessfully(int)" (?ExitedUnsuccessfully@internal@testing@@YA_NH@Z)，该符号在函数 __catch$?TestBody@ContainerUtilityDeathTest_ShuffleRange_Test@?A0x1795f68d@@EAEXXZ$3 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "void __cdecl testing::internal2::PrintBytesInObjectTo(unsigned char const *,unsigned int,class std::basic_ostream<char,struct std::char_traits<char> > *)" (?PrintBytesInObjectTo@internal2@testing@@YAXPBEIPAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)，该符号在函数 "class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl testing::internal2::operator<<<char,struct std::char_traits<char>,class `anonymous namespace'::UnprintableChar>(class std::basic_ostream<char,struct std::char_traits<char> > &,class `anonymous namespace'::UnprintableChar const &)" (??$?6DU?$char_traits@D@std@@VUnprintableChar@?A0x1795f68d@@@internal2@testing@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AAV23@ABVUnprintableChar@?A0x1795f68d@@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "void __cdecl testing::internal::PrintTo(unsigned char,class std::basic_ostream<char,struct std::char_traits<char> > *)" (?PrintTo@internal@testing@@YAXEPAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)，该符号在函数 "void __cdecl testing::internal::UniversalPrint<char>(char const &,class std::basic_ostream<char,struct std::char_traits<char> > *)" (??$UniversalPrint@D@internal@testing@@YAXABDPAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "void __cdecl testing::internal::PrintTo(wchar_t,class std::basic_ostream<char,struct std::char_traits<char> > *)" (?PrintTo@internal@testing@@YAX_WPAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)，该符号在函数 "void __cdecl testing::internal::UniversalPrint<wchar_t>(wchar_t const &,class std::basic_ostream<char,struct std::char_traits<char> > *)" (??$UniversalPrint@_W@internal@testing@@YAXAB_WPAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "void __cdecl testing::internal::PrintStringTo(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_ostream<char,struct std::char_traits<char> > *)" (?PrintStringTo@internal@testing@@YAXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PAV?$basic_ostream@DU?$char_traits@D@std@@@4@@Z)，该符号在函数 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl testing::PrintToString<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??$PrintToString@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@testing@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV12@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "void __cdecl testing::internal::PrintWideStringTo(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::basic_ostream<char,struct std::char_traits<char> > *)" (?PrintWideStringTo@internal@testing@@YAXABV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@PAV?$basic_ostream@DU?$char_traits@D@std@@@4@@Z)，该符号在函数 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl testing::PrintToString<class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > >(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &)" (??$PrintToString@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@testing@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@2@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "void __cdecl testing::internal::ReportInvalidTestCaseType(char const *,struct testing::internal::CodeLocation)" (?ReportInvalidTestCaseType@internal@testing@@YAXPBDUCodeLocation@12@@Z)，该符号在函数 "public: class testing::internal::ParameterizedTestCaseInfo<class testing::CodeLocationForTESTP> * __thiscall testing::internal::ParameterizedTestCaseRegistry::GetTestCasePatternHolder<class testing::CodeLocationForTESTP>(char const *,struct testing::internal::CodeLocation)" (??$GetTestCasePatternHolder@VCodeLocationForTESTP@testing@@@ParameterizedTestCaseRegistry@internal@testing@@QAEPAV?$ParameterizedTestCaseInfo@VCodeLocationForTESTP@testing@@@12@PBDUCodeLocation@12@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "private: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl testing::TestPartResult::ExtractSummary(char const *)" (?ExtractSummary@TestPartResult@testing@@CA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PBD@Z)，该符号在函数 "public: __thiscall testing::TestPartResult::TestPartResult(enum testing::TestPartResult::Type,char const *,int,char const *)" (??0TestPartResult@testing@@QAE@W4Type@01@PBDH1@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: class testing::TestPartResult const & __thiscall testing::TestPartResultArray::GetTestPartResult(int)const " (?GetTestPartResult@TestPartResultArray@testing@@QBEABVTestPartResult@2@H@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::NoFatalFailureTest_AssertNoFatalFailureOnFatalFailure_Test::TestBody(void)" (?TestBody@NoFatalFailureTest_AssertNoFatalFailureOnFatalFailure_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: int __thiscall testing::TestPartResultArray::size(void)const " (?size@TestPartResultArray@testing@@QBEHXZ)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::NoFatalFailureTest_AssertNoFatalFailureOnFatalFailure_Test::TestBody(void)" (?TestBody@NoFatalFailureTest_AssertNoFatalFailureOnFatalFailure_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall testing::internal::HasNewFatalFailureHelper::HasNewFatalFailureHelper(void)" (??0HasNewFatalFailureHelper@internal@testing@@QAE@XZ)，该符号在函数 "protected: void __thiscall `anonymous namespace'::NoFatalFailureTest::DoAssertNoFatalFailureOnFails(void)" (?DoAssertNoFatalFailureOnFails@NoFatalFailureTest@?A0x1795f68d@@IAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: virtual __thiscall testing::internal::HasNewFatalFailureHelper::~HasNewFatalFailureHelper(void)" (??1HasNewFatalFailureHelper@internal@testing@@UAE@XZ)，该符号在函数 "protected: void __thiscall `anonymous namespace'::NoFatalFailureTest::DoAssertNoFatalFailureOnFails(void)" (?DoAssertNoFatalFailureOnFails@NoFatalFailureTest@?A0x1795f68d@@IAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall testing::AssertionResult::AssertionResult(class testing::AssertionResult const &)" (??0AssertionResult@testing@@QAE@ABV01@@Z)，该符号在函数 "class testing::AssertionResult __cdecl testing::AssertPred1Helper<bool (__cdecl*)(class TestingVector const &),class TestingVector>(char const *,char const *,bool (__cdecl*)(class TestingVector const &),class TestingVector const &)" (??$AssertPred1Helper@P6A_NABVTestingVector@@@ZV1@@testing@@YA?AVAssertionResult@0@PBD0P6A_NABVTestingVector@@@Z1@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: class testing::AssertionResult __thiscall testing::AssertionResult::operator!(void)const " (??7AssertionResult@testing@@QBE?AV01@XZ)，该符号在函数 "public: static void __cdecl `private: virtual void __thiscall `anonymous namespace'::AssertionTest_AssertFalseWithAssertionResult_Test::TestBody(void)'::`8'::GTestExpectFatalFailureHelper::Execute(void)" (?Execute@GTestExpectFatalFailureHelper@?7??TestBody@AssertionTest_AssertFalseWithAssertionResult_Test@?A0x1795f68d@@EAEXXZ@SAXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::AssertionSuccess(void)" (?AssertionSuccess@testing@@YA?AVAssertionResult@1@XZ)，该符号在函数 "class testing::AssertionResult __cdecl testing::AssertPred1Helper<bool (__cdecl*)(class TestingVector const &),class TestingVector>(char const *,char const *,bool (__cdecl*)(class TestingVector const &),class TestingVector const &)" (??$AssertPred1Helper@P6A_NABVTestingVector@@@ZV1@@testing@@YA?AVAssertionResult@0@PBD0P6A_NABVTestingVector@@@Z1@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::AssertionFailure(void)" (?AssertionFailure@testing@@YA?AVAssertionResult@1@XZ)，该符号在函数 "class testing::AssertionResult __cdecl testing::AssertPred1Helper<bool (__cdecl*)(class TestingVector const &),class TestingVector>(char const *,char const *,bool (__cdecl*)(class TestingVector const &),class TestingVector const &)" (??$AssertPred1Helper@P6A_NABVTestingVector@@@ZV1@@testing@@YA?AVAssertionResult@0@PBD0P6A_NABVTestingVector@@@Z1@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::AssertionFailure(class testing::Message const &)" (?AssertionFailure@testing@@YA?AVAssertionResult@1@ABVMessage@1@@Z)，该符号在函数 "class testing::AssertionResult __cdecl `anonymous namespace'::EqualsFormat<int,int>(char const *,char const *,int const &,int const &)" (??$EqualsFormat@HH@?A0x1795f68d@@YA?AVAssertionResult@testing@@PBD0ABH1@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: virtual __thiscall testing::Test::~Test(void)" (??1Test@testing@@UAE@XZ)，该符号在函数 __unwindfunclet$??0UnitTestRecordPropertyTestHelper@internal@testing@@IAE@XZ$0 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: static bool __cdecl testing::Test::HasFatalFailure(void)" (?HasFatalFailure@Test@testing@@SA_NXZ)，该符号在函数 "public: static bool __cdecl testing::Test::HasFailure(void)" (?HasFailure@Test@testing@@SA_NXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: static bool __cdecl testing::Test::HasNonfatalFailure(void)" (?HasNonfatalFailure@Test@testing@@SA_NXZ)，该符号在函数 "public: static bool __cdecl testing::Test::HasFailure(void)" (?HasFailure@Test@testing@@SA_NXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: static void __cdecl testing::Test::RecordProperty(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?RecordProperty@Test@testing@@SAXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z)，该符号在函数 "void __cdecl `anonymous namespace'::ExpectNonFatalFailureRecordingPropertyWithReservedKey(class testing::TestResult const &,char const *)" (?ExpectNonFatalFailureRecordingPropertyWithReservedKey@?A0x1795f68d@@YAXABVTestResult@testing@@PBD@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "protected: __thiscall testing::Test::Test(void)" (??0Test@testing@@IAE@XZ)，该符号在函数 "public: __thiscall testing::CodeLocationForTYPEDTEST<int>::CodeLocationForTYPEDTEST<int>(void)" (??0?$CodeLocationForTYPEDTEST@H@testing@@QAE@XZ) 中被引用
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "protected: virtual void __thiscall testing::Test::SetUp(void)" (?SetUp@Test@testing@@MAEXXZ)
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "protected: virtual void __thiscall testing::Test::TearDown(void)" (?TearDown@Test@testing@@MAEXXZ)，该符号在函数 "public: virtual void __thiscall testing::FlagfileTest::TearDown(void)" (?TearDown@FlagfileTest@testing@@UAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall testing::TestResult::TestResult(void)" (??0TestResult@testing@@QAE@XZ)，该符号在函数 "protected: virtual void __thiscall `anonymous namespace'::TestResultTest::SetUp(void)" (?SetUp@TestResultTest@?A0x1795f68d@@MAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall testing::TestResult::~TestResult(void)" (??1TestResult@testing@@QAE@XZ)，该符号在函数 "public: void * __thiscall testing::TestResult::`scalar deleting destructor'(unsigned int)" (??_GTestResult@testing@@QAEPAXI@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: int __thiscall testing::TestResult::total_part_count(void)const " (?total_part_count@TestResult@testing@@QBEHXZ)，该符号在函数 "private: virtual void __thiscall testing::SuccessfulAssertionTest_ASSERT_STR_Test::TestBody(void)" (?TestBody@SuccessfulAssertionTest_ASSERT_STR_Test@testing@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: int __thiscall testing::TestResult::test_property_count(void)const " (?test_property_count@TestResult@testing@@QBEHXZ)，该符号在函数 "void __cdecl `anonymous namespace'::ExpectNonFatalFailureRecordingPropertyWithReservedKey(class testing::TestResult const &,char const *)" (?ExpectNonFatalFailureRecordingPropertyWithReservedKey@?A0x1795f68d@@YAXABVTestResult@testing@@PBD@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: bool __thiscall testing::TestResult::Failed(void)const " (?Failed@TestResult@testing@@QBE_NXZ)，该符号在函数 "public: bool __thiscall testing::TestResult::Passed(void)const " (?Passed@TestResult@testing@@QBE_NXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: class testing::TestPartResult const & __thiscall testing::TestResult::GetTestPartResult(int)const " (?GetTestPartResult@TestResult@testing@@QBEABVTestPartResult@2@H@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::TestResultDeathTest_GetTestPartResult_Test::TestBody(void)" (?TestBody@TestResultDeathTest_GetTestPartResult_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: class testing::TestProperty const & __thiscall testing::TestResult::GetTestProperty(int)const " (?GetTestProperty@TestResult@testing@@QBEABVTestProperty@2@H@Z)，该符号在函数 "public: static void __cdecl `anonymous namespace'::UnitTestRecordPropertyTest::SetUpTestCase(void)" (?SetUpTestCase@UnitTestRecordPropertyTest@?A0x1795f68d@@SAXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "private: void __thiscall testing::TestResult::RecordProperty(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class testing::TestProperty const &)" (?RecordProperty@TestResult@testing@@AAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABVTestProperty@2@@Z)，该符号在函数 "public: static void __cdecl testing::internal::TestResultAccessor::RecordProperty(class testing::TestResult *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class testing::TestProperty const &)" (?RecordProperty@TestResultAccessor@internal@testing@@SAXPAVTestResult@3@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABVTestProperty@3@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "private: void __thiscall testing::TestResult::ClearTestPartResults(void)" (?ClearTestPartResults@TestResult@testing@@AAEXXZ)，该符号在函数 "void __cdecl `anonymous namespace'::ClearCurrentTestPartResults(void)" (?ClearCurrentTestPartResults@?A0x1795f68d@@YAXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: int __thiscall testing::TestCase::total_test_count(void)const " (?total_test_count@TestCase@testing@@QBEHXZ)，该符号在函数 "protected: static class testing::TestInfo const * __cdecl testing::TestInfoTest::GetTestInfo(char const *)" (?GetTestInfo@TestInfoTest@testing@@KAPBVTestInfo@2@PBD@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: class testing::TestInfo const * __thiscall testing::TestCase::GetTestInfo(int)const " (?GetTestInfo@TestCase@testing@@QBEPBVTestInfo@2@H@Z)，该符号在函数 "protected: static class testing::TestInfo const * __cdecl testing::TestInfoTest::GetTestInfo(char const *)" (?GetTestInfo@TestInfoTest@testing@@KAPBVTestInfo@2@PBD@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall testing::TestEventListeners::TestEventListeners(void)" (??0TestEventListeners@testing@@QAE@XZ)，该符号在函数 "private: virtual void __thiscall EventListenerTest_AppendKeepsOrder_Test::TestBody(void)" (?TestBody@EventListenerTest_AppendKeepsOrder_Test@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall testing::TestEventListeners::~TestEventListeners(void)" (??1TestEventListeners@testing@@QAE@XZ)，该符号在函数 "private: virtual void __thiscall EventListenerTest_AppendKeepsOrder_Test::TestBody(void)" (?TestBody@EventListenerTest_AppendKeepsOrder_Test@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: void __thiscall testing::TestEventListeners::Append(class testing::TestEventListener *)" (?Append@TestEventListeners@testing@@QAEXPAVTestEventListener@2@@Z)，该符号在函数 "private: virtual void __thiscall EventListenerTest_AppendKeepsOrder_Test::TestBody(void)" (?TestBody@EventListenerTest_AppendKeepsOrder_Test@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: class testing::TestEventListener * __thiscall testing::TestEventListeners::Release(class testing::TestEventListener *)" (?Release@TestEventListeners@testing@@QAEPAVTestEventListener@2@PAV32@@Z)，该符号在函数 "private: virtual void __thiscall EventListenerTest_RemovingDefaultResultPrinterWorks_Test::TestBody(void)" (?TestBody@EventListenerTest_RemovingDefaultResultPrinterWorks_Test@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "private: class testing::TestEventListener * __thiscall testing::TestEventListeners::repeater(void)" (?repeater@TestEventListeners@testing@@AAEPAVTestEventListener@2@XZ)，该符号在函数 "public: static class testing::TestEventListener * __cdecl testing::internal::TestEventListenersAccessor::GetRepeater(class testing::TestEventListeners *)" (?GetRepeater@TestEventListenersAccessor@internal@testing@@SAPAVTestEventListener@3@PAVTestEventListeners@3@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "private: void __thiscall testing::TestEventListeners::SetDefaultResultPrinter(class testing::TestEventListener *)" (?SetDefaultResultPrinter@TestEventListeners@testing@@AAEXPAVTestEventListener@2@@Z)，该符号在函数 "public: static void __cdecl testing::internal::TestEventListenersAccessor::SetDefaultResultPrinter(class testing::TestEventListeners *,class testing::TestEventListener *)" (?SetDefaultResultPrinter@TestEventListenersAccessor@internal@testing@@SAXPAVTestEventListeners@3@PAVTestEventListener@3@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "private: void __thiscall testing::TestEventListeners::SetDefaultXmlGenerator(class testing::TestEventListener *)" (?SetDefaultXmlGenerator@TestEventListeners@testing@@AAEXPAVTestEventListener@2@@Z)，该符号在函数 "public: static void __cdecl testing::internal::TestEventListenersAccessor::SetDefaultXmlGenerator(class testing::TestEventListeners *,class testing::TestEventListener *)" (?SetDefaultXmlGenerator@TestEventListenersAccessor@internal@testing@@SAXPAVTestEventListeners@3@PAVTestEventListener@3@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "private: bool __thiscall testing::TestEventListeners::EventForwardingEnabled(void)const " (?EventForwardingEnabled@TestEventListeners@testing@@ABE_NXZ)，该符号在函数 "public: static bool __cdecl testing::internal::TestEventListenersAccessor::EventForwardingEnabled(class testing::TestEventListeners const &)" (?EventForwardingEnabled@TestEventListenersAccessor@internal@testing@@SA_NABVTestEventListeners@3@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "private: void __thiscall testing::TestEventListeners::SuppressEventForwarding(void)" (?SuppressEventForwarding@TestEventListeners@testing@@AAEXXZ)，该符号在函数 "public: static void __cdecl testing::internal::TestEventListenersAccessor::SuppressEventForwarding(class testing::TestEventListeners *)" (?SuppressEventForwarding@TestEventListenersAccessor@internal@testing@@SAXPAVTestEventListeners@3@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: static class testing::UnitTest * __cdecl testing::UnitTest::GetInstance(void)" (?GetInstance@UnitTest@testing@@SAPAV12@XZ)，该符号在函数 "void __cdecl testing::`dynamic initializer for 'gtest_CodeLocationForTESTP_dummy_''(void)" (??__Egtest_CodeLocationForTESTP_dummy_@testing@@YAXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: char const * __thiscall testing::UnitTest::original_working_dir(void)const " (?original_working_dir@UnitTest@testing@@QBEPBDXZ)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::UnitTestTest_CanGetOriginalWorkingDir_Test::TestBody(void)" (?TestBody@UnitTestTest_CanGetOriginalWorkingDir_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: class testing::TestCase const * __thiscall testing::UnitTest::current_test_case(void)const " (?current_test_case@UnitTest@testing@@QBEPBVTestCase@2@XZ)，该符号在函数 "void __cdecl `anonymous namespace'::ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTestCase(char const *)" (?ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTestCase@?A0x1795f68d@@YAXPBD@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: class testing::TestInfo const * __thiscall testing::UnitTest::current_test_info(void)const " (?current_test_info@UnitTest@testing@@QBEPBVTestInfo@2@XZ)，该符号在函数 "void __cdecl `anonymous namespace'::ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTest(char const *)" (?ExpectNonFatalFailureRecordingPropertyWithReservedKeyForCurrentTest@?A0x1795f68d@@YAXPBD@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: class testing::internal::ParameterizedTestCaseRegistry & __thiscall testing::UnitTest::parameterized_test_registry(void)" (?parameterized_test_registry@UnitTest@testing@@QAEAAVParameterizedTestCaseRegistry@internal@2@XZ)，该符号在函数 "void __cdecl testing::`dynamic initializer for 'gtest_CodeLocationForTESTP_dummy_''(void)" (??__Egtest_CodeLocationForTESTP_dummy_@testing@@YAXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: __int64 __thiscall testing::UnitTest::start_timestamp(void)const " (?start_timestamp@UnitTest@testing@@QBE_JXZ)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::UnitTestTest_ReturnsPlausibleTimestamp_Test::TestBody(void)" (?TestBody@UnitTestTest_ReturnsPlausibleTimestamp_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: class testing::TestResult const & __thiscall testing::UnitTest::ad_hoc_test_result(void)const " (?ad_hoc_test_result@UnitTest@testing@@QBEABVTestResult@2@XZ)，该符号在函数 "void __cdecl `anonymous namespace'::ExpectNonFatalFailureRecordingPropertyWithReservedKeyOutsideOfTestCase(char const *)" (?ExpectNonFatalFailureRecordingPropertyWithReservedKeyOutsideOfTestCase@?A0x1795f68d@@YAXPBD@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "private: class testing::Environment * __thiscall testing::UnitTest::AddEnvironment(class testing::Environment *)" (?AddEnvironment@UnitTest@testing@@AAEPAVEnvironment@2@PAV32@@Z)，该符号在函数 "void __cdecl `anonymous namespace'::`dynamic initializer for 'record_property_env''(void)" (??__Erecord_property_env@?A0x1795f68d@@YAXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "private: void __thiscall testing::UnitTest::RecordProperty(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?RecordProperty@UnitTest@testing@@AAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z)，该符号在函数 "protected: void __thiscall testing::internal::UnitTestRecordPropertyTestHelper::UnitTestRecordProperty(char const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?UnitTestRecordProperty@UnitTestRecordPropertyTestHelper@internal@testing@@IAEXPBDABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "private: __thiscall testing::UnitTest::UnitTest(void)" (??0UnitTest@testing@@AAE@XZ)，该符号在函数 "protected: __thiscall testing::internal::UnitTestRecordPropertyTestHelper::UnitTestRecordPropertyTestHelper(void)" (??0UnitTestRecordPropertyTestHelper@internal@testing@@IAE@XZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "private: virtual __thiscall testing::UnitTest::~UnitTest(void)" (??1UnitTest@testing@@EAE@XZ)，该符号在函数 "public: virtual __thiscall testing::internal::UnitTestRecordPropertyTestHelper::~UnitTestRecordPropertyTestHelper(void)" (??1UnitTestRecordPropertyTestHelper@internal@testing@@UAE@XZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::internal::CmpHelperEQ(char const *,char const *,__int64,__int64)" (?CmpHelperEQ@internal@testing@@YA?AVAssertionResult@2@PBD0_J1@Z)，该符号在函数 "public: static class testing::AssertionResult __cdecl testing::internal::EqHelper<1>::Compare<__int64,__int64>(char const *,char const *,__int64 const &,__int64 const &,void *)" (??$Compare@_J_J@?$EqHelper@$00@internal@testing@@SA?AVAssertionResult@2@PBD0AB_J1PAX@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::internal::CmpHelperLE(char const *,char const *,__int64,__int64)" (?CmpHelperLE@internal@testing@@YA?AVAssertionResult@2@PBD0_J1@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::UnitTestTest_ReturnsPlausibleTimestamp_Test::TestBody(void)" (?TestBody@UnitTestTest_ReturnsPlausibleTimestamp_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::internal::CmpHelperSTREQ(char const *,char const *,char const *,char const *)" (?CmpHelperSTREQ@internal@testing@@YA?AVAssertionResult@2@PBD000@Z)，该符号在函数 "protected: static void __cdecl testing::InitGoogleTestTest::AssertStringArrayEq<char const >(unsigned int,char const * *,unsigned int,char const * *)" (??$AssertStringArrayEq@$$CBD@InitGoogleTestTest@testing@@KAXIPAPBDI0@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::internal::CmpHelperSTRCASEEQ(char const *,char const *,char const *,char const *)" (?CmpHelperSTRCASEEQ@internal@testing@@YA?AVAssertionResult@2@PBD000@Z)，该符号在函数 "public: static void __cdecl `private: virtual void __thiscall `anonymous namespace'::StringAssertionTest_ASSERT_STRCASEEQ_Test::TestBody(void)'::`16'::GTestExpectFatalFailureHelper::Execute(void)" (?Execute@GTestExpectFatalFailureHelper@?BA@??TestBody@StringAssertionTest_ASSERT_STRCASEEQ_Test@?A0x1795f68d@@EAEXXZ@SAXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::internal::CmpHelperSTRNE(char const *,char const *,char const *,char const *)" (?CmpHelperSTRNE@internal@testing@@YA?AVAssertionResult@2@PBD000@Z)，该符号在函数 "public: static void __cdecl `private: virtual void __thiscall StreamingAssertionsTest_StringsNotEqual_Test::TestBody(void)'::`22'::GTestExpectFatalFailureHelper::Execute(void)" (?Execute@GTestExpectFatalFailureHelper@?BG@??TestBody@StreamingAssertionsTest_StringsNotEqual_Test@@EAEXXZ@SAXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::internal::CmpHelperSTRCASENE(char const *,char const *,char const *,char const *)" (?CmpHelperSTRCASENE@internal@testing@@YA?AVAssertionResult@2@PBD000@Z)，该符号在函数 "public: static void __cdecl `private: virtual void __thiscall `anonymous namespace'::AssertionWithMessageTest_ASSERT_STR_Test::TestBody(void)'::`16'::GTestExpectFatalFailureHelper::Execute(void)" (?Execute@GTestExpectFatalFailureHelper@?BA@??TestBody@AssertionWithMessageTest_ASSERT_STR_Test@?A0x1795f68d@@EAEXXZ@SAXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::internal::CmpHelperSTREQ(char const *,char const *,wchar_t const *,wchar_t const *)" (?CmpHelperSTREQ@internal@testing@@YA?AVAssertionResult@2@PBD0PB_W1@Z)，该符号在函数 "protected: static void __cdecl testing::InitGoogleTestTest::AssertStringArrayEq<wchar_t const >(unsigned int,wchar_t const * *,unsigned int,wchar_t const * *)" (??$AssertStringArrayEq@$$CB_W@InitGoogleTestTest@testing@@KAXIPAPB_WI0@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::internal::CmpHelperSTRNE(char const *,char const *,wchar_t const *,wchar_t const *)" (?CmpHelperSTRNE@internal@testing@@YA?AVAssertionResult@2@PBD0PB_W1@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::StringAssertionTest_STRNE_Wide_Test::TestBody(void)" (?TestBody@StringAssertionTest_STRNE_Wide_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::IsSubstring(char const *,char const *,char const *,char const *)" (?IsSubstring@testing@@YA?AVAssertionResult@1@PBD000@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::IsSubstringTest_GeneratesCorrectMessageForCString_Test::TestBody(void)" (?TestBody@IsSubstringTest_GeneratesCorrectMessageForCString_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::IsSubstring(char const *,char const *,wchar_t const *,wchar_t const *)" (?IsSubstring@testing@@YA?AVAssertionResult@1@PBD0PB_W1@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::IsSubstringTest_ReturnsCorrectResultForWideCString_Test::TestBody(void)" (?TestBody@IsSubstringTest_ReturnsCorrectResultForWideCString_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::IsNotSubstring(char const *,char const *,char const *,char const *)" (?IsNotSubstring@testing@@YA?AVAssertionResult@1@PBD000@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::IsNotSubstringTest_ReturnsCorrectResultForCString_Test::TestBody(void)" (?TestBody@IsNotSubstringTest_ReturnsCorrectResultForCString_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::IsNotSubstring(char const *,char const *,wchar_t const *,wchar_t const *)" (?IsNotSubstring@testing@@YA?AVAssertionResult@1@PBD0PB_W1@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::IsNotSubstringTest_GeneratesCorrectMessageForWideCString_Test::TestBody(void)" (?TestBody@IsNotSubstringTest_GeneratesCorrectMessageForWideCString_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::IsSubstring(char const *,char const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?IsSubstring@testing@@YA?AVAssertionResult@1@PBD0ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z)，该符号在函数 "protected: static void __cdecl testing::InitGoogleTestTest::TestParsingFlags<char>(int,char const * *,int,char const * *,struct testing::Flags const &,bool)" (??$TestParsingFlags@D@InitGoogleTestTest@testing@@KAXHPAPBDH0ABUFlags@1@_N@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::IsNotSubstring(char const *,char const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?IsNotSubstring@testing@@YA?AVAssertionResult@1@PBD0ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z)，该符号在函数 "protected: static void __cdecl testing::InitGoogleTestTest::TestParsingFlags<char>(int,char const * *,int,char const * *,struct testing::Flags const &,bool)" (??$TestParsingFlags@D@InitGoogleTestTest@testing@@KAXHPAPBDH0ABUFlags@1@_N@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::IsSubstring(char const *,char const *,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &)" (?IsSubstring@testing@@YA?AVAssertionResult@1@PBD0ABV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@1@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::IsSubstringTest_GeneratesCorrectMessageForWstring_Test::TestBody(void)" (?TestBody@IsSubstringTest_GeneratesCorrectMessageForWstring_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::IsNotSubstring(char const *,char const *,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &)" (?IsNotSubstring@testing@@YA?AVAssertionResult@1@PBD0ABV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@1@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::IsNotSubstringTest_ReturnsCorrectResultForStdWstring_Test::TestBody(void)" (?TestBody@IsNotSubstringTest_ReturnsCorrectResultForStdWstring_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::internal::DoubleNearPredFormat(char const *,char const *,char const *,double,double,double)" (?DoubleNearPredFormat@internal@testing@@YA?AVAssertionResult@2@PBD00NNN@Z)，该符号在函数 "public: static void __cdecl `private: virtual void __thiscall `anonymous namespace'::AssertionWithMessageTest_ASSERT_FLOATING_Test::TestBody(void)'::`12'::GTestExpectFatalFailureHelper::Execute(void)" (?Execute@GTestExpectFatalFailureHelper@?M@??TestBody@AssertionWithMessageTest_ASSERT_FLOATING_Test@?A0x1795f68d@@EAEXXZ@SAXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall testing::internal::AssertHelper::AssertHelper(enum testing::TestPartResult::Type,char const *,int,char const *)" (??0AssertHelper@internal@testing@@QAE@W4Type@TestPartResult@2@PBDH1@Z)，该符号在函数 "protected: static void __cdecl testing::InitGoogleTestTest::AssertStringArrayEq<char const >(unsigned int,char const * *,unsigned int,char const * *)" (??$AssertStringArrayEq@$$CBD@InitGoogleTestTest@testing@@KAXIPAPBDI0@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall testing::internal::AssertHelper::~AssertHelper(void)" (??1AssertHelper@internal@testing@@QAE@XZ)，该符号在函数 "protected: static void __cdecl testing::InitGoogleTestTest::AssertStringArrayEq<char const >(unsigned int,char const * *,unsigned int,char const * *)" (??$AssertStringArrayEq@$$CBD@InitGoogleTestTest@testing@@KAXIPAPBDI0@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: void __thiscall testing::internal::AssertHelper::operator=(class testing::Message const &)const " (??4AssertHelper@internal@testing@@QBEXABVMessage@2@@Z)，该符号在函数 "protected: static void __cdecl testing::InitGoogleTestTest::AssertStringArrayEq<char const >(unsigned int,char const * *,unsigned int,char const * *)" (??$AssertStringArrayEq@$$CBD@InitGoogleTestTest@testing@@KAXIPAPBDI0@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::FloatLE(char const *,char const *,float,float)" (?FloatLE@testing@@YA?AVAssertionResult@1@PBD0MM@Z)，该符号在函数 "public: static void __cdecl `private: virtual void __thiscall `anonymous namespace'::FloatTest_FloatLEFails_Test::TestBody(void)'::`47'::GTestExpectFatalFailureHelper::Execute(void)" (?Execute@GTestExpectFatalFailureHelper@?CP@??TestBody@FloatTest_FloatLEFails_Test@?A0x1795f68d@@EAEXXZ@SAXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::AssertionResult __cdecl testing::DoubleLE(char const *,char const *,double,double)" (?DoubleLE@testing@@YA?AVAssertionResult@1@PBD0NN@Z)，该符号在函数 "public: static void __cdecl `private: virtual void __thiscall `anonymous namespace'::DoubleTest_DoubleLEFails_Test::TestBody(void)'::`47'::GTestExpectFatalFailureHelper::Execute(void)" (?Execute@GTestExpectFatalFailureHelper@?CP@??TestBody@DoubleTest_DoubleLEFails_Test@?A0x1795f68d@@EAEXXZ@SAXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall testing::ScopedFakeTestPartResultReporter::ScopedFakeTestPartResultReporter(class testing::TestPartResultArray *)" (??0ScopedFakeTestPartResultReporter@testing@@QAE@PAVTestPartResultArray@1@@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::NoFatalFailureTest_AssertNoFatalFailureOnFatalFailure_Test::TestBody(void)" (?TestBody@NoFatalFailureTest_AssertNoFatalFailureOnFatalFailure_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall testing::ScopedFakeTestPartResultReporter::ScopedFakeTestPartResultReporter(enum testing::ScopedFakeTestPartResultReporter::InterceptMode,class testing::TestPartResultArray *)" (??0ScopedFakeTestPartResultReporter@testing@@QAE@W4InterceptMode@01@PAVTestPartResultArray@1@@Z)，该符号在函数 "void __cdecl `anonymous namespace'::DoesNotAbortHelper(bool *)" (?DoesNotAbortHelper@?A0x1795f68d@@YAXPA_N@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: virtual __thiscall testing::ScopedFakeTestPartResultReporter::~ScopedFakeTestPartResultReporter(void)" (??1ScopedFakeTestPartResultReporter@testing@@UAE@XZ)，该符号在函数 "void __cdecl `anonymous namespace'::DoesNotAbortHelper(bool *)" (?DoesNotAbortHelper@?A0x1795f68d@@YAXPA_N@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall testing::internal::SingleFailureChecker::SingleFailureChecker(class testing::TestPartResultArray const *,enum testing::TestPartResult::Type,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0SingleFailureChecker@internal@testing@@QAE@PBVTestPartResultArray@2@W4Type@TestPartResult@2@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)，该符号在函数 "void __cdecl `anonymous namespace'::DoesNotAbortHelper(bool *)" (?DoesNotAbortHelper@?A0x1795f68d@@YAXPA_N@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall testing::internal::SingleFailureChecker::~SingleFailureChecker(void)" (??1SingleFailureChecker@internal@testing@@QAE@XZ)，该符号在函数 "void __cdecl `anonymous namespace'::DoesNotAbortHelper(bool *)" (?DoesNotAbortHelper@?A0x1795f68d@@YAXPA_N@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "__int64 __cdecl testing::internal::GetTimeInMillis(void)" (?GetTimeInMillis@internal@testing@@YA_JXZ)，该符号在函数 "int __cdecl testing::internal::GetRandomSeedFromFlag(int)" (?GetRandomSeedFromFlag@internal@testing@@YAHH@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "bool __cdecl testing::internal::ShouldUseColor(bool)" (?ShouldUseColor@internal@testing@@YA_N_N@Z)，该符号在函数 "private: virtual void __thiscall ColoredOutputTest_UsesColorsWhenGTestColorFlagIsAliasOfYes_Test::TestBody(void)" (?TestBody@ColoredOutputTest_UsesColorsWhenGTestColorFlagIsAliasOfYes_Test@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl testing::internal::FormatTimeInMillisAsSeconds(__int64)" (?FormatTimeInMillisAsSeconds@internal@testing@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_J@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::FormatTimeInMillisAsSecondsTest_FormatsNegativeNumber_Test::TestBody(void)" (?TestBody@FormatTimeInMillisAsSecondsTest_FormatsNegativeNumber_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl testing::internal::FormatEpochTimeInMillisAsIso8601(__int64)" (?FormatEpochTimeInMillisAsIso8601@internal@testing@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_J@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::FormatEpochTimeInMillisAsIso8601Test_MillisecondsDoNotAffectResult_Test::TestBody(void)" (?TestBody@FormatEpochTimeInMillisAsIso8601Test_MillisecondsDoNotAffectResult_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "bool __cdecl testing::internal::ParseInt32Flag(char const *,char const *,int *)" (?ParseInt32Flag@internal@testing@@YA_NPBD0PAH@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::ParseInt32FlagTest_ParsesAndReturnsValidValue_Test::TestBody(void)" (?TestBody@ParseInt32FlagTest_ParsesAndReturnsValidValue_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl testing::internal::CodePointToUtf8(unsigned int)" (?CodePointToUtf8@internal@testing@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@I@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::CodePointToUtf8Test_CanEncode12To16Bits_Test::TestBody(void)" (?TestBody@CodePointToUtf8Test_CanEncode12To16Bits_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl testing::internal::WideStringToUtf8(wchar_t const *,int)" (?WideStringToUtf8@internal@testing@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PB_WH@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::WideStringToUtf8Test_CanEncode12To16Bits_Test::TestBody(void)" (?TestBody@WideStringToUtf8Test_CanEncode12To16Bits_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "bool __cdecl testing::internal::ShouldShard(char const *,char const *,bool)" (?ShouldShard@internal@testing@@YA_NPBD0_N@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::ShouldShardDeathTest_AbortsWhenShardingEnvVarsAreInvalid_Test::TestBody(void)" (?TestBody@ShouldShardDeathTest_AbortsWhenShardingEnvVarsAreInvalid_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "int __cdecl testing::internal::Int32FromEnvOrDie(char const *,int)" (?Int32FromEnvOrDie@internal@testing@@YAHPBDH@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::Int32FromEnvOrDieDeathTest_AbortsOnFailure_Test::TestBody(void)" (?TestBody@Int32FromEnvOrDieDeathTest_AbortsOnFailure_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "bool __cdecl testing::internal::ShouldRunTestOnShard(int,int,int)" (?ShouldRunTestOnShard@internal@testing@@YA_NHHH@Z)，该符号在函数 "private: virtual void __thiscall `anonymous namespace'::ShouldRunTestOnShardTest_IsPartitionWhenThereAreFiveShards_Test::TestBody(void)" (?TestBody@ShouldRunTestOnShardTest_IsPartitionWhenThereAreFiveShards_Test@?A0x1795f68d@@EAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "class testing::internal::FilePath __cdecl testing::internal::GetCurrentExecutableName(void)" (?GetCurrentExecutableName@internal@testing@@YA?AVFilePath@12@XZ)，该符号在函数 "public: virtual void __thiscall testing::FlagfileTest::SetUp(void)" (?SetUp@FlagfileTest@testing@@UAEXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: class testing::TestResult * __thiscall testing::internal::UnitTestImpl::current_test_result(void)" (?current_test_result@UnitTestImpl@internal@testing@@QAEPAVTestResult@3@XZ)，该符号在函数 "void __cdecl `anonymous namespace'::ClearCurrentTestPartResults(void)" (?ClearCurrentTestPartResults@?A0x1795f68d@@YAXXZ) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "public: class testing::TestCase * __thiscall testing::internal::UnitTestImpl::GetTestCase(char const *,char const *,void (__cdecl*)(void),void (__cdecl*)(void))" (?GetTestCase@UnitTestImpl@internal@testing@@QAEPAVTestCase@3@PBD0P6AXXZ1@Z)，该符号在函数 "protected: static class testing::TestInfo const * __cdecl testing::TestInfoTest::GetTestInfo(char const *)" (?GetTestInfo@TestInfoTest@testing@@KAPBVTestInfo@2@PBD@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "void __cdecl testing::internal::ParseGoogleTestFlagsOnly(int *,char * *)" (?ParseGoogleTestFlagsOnly@internal@testing@@YAXPAHPAPAD@Z)，该符号在函数 "protected: static void __cdecl testing::InitGoogleTestTest::TestParsingFlags<char>(int,char const * *,int,char const * *,struct testing::Flags const &,bool)" (??$TestParsingFlags@D@InitGoogleTestTest@testing@@KAXHPAPBDH0ABUFlags@1@_N@Z) 中被引用
     1>gtest_unittest.obj : error LNK2019: 无法解析的外部符号 "void __cdecl testing::internal::ParseGoogleTestFlagsOnly(int *,wchar_t * *)" (?ParseGoogleTestFlagsOnly@internal@testing@@YAXPAHPAPA_W@Z)，该符号在函数 "protected: static void __cdecl testing::InitGoogleTestTest::TestParsingFlags<wchar_t>(int,wchar_t const * *,int,wchar_t const * *,struct testing::Flags const &,bool)" (??$TestParsingFlags@_W@InitGoogleTestTest@testing@@KAXHPAPB_WH0ABUFlags@1@_N@Z) 中被引用
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > testing::internal::FLAGS_gtest_internal_run_death_test" (?FLAGS_gtest_internal_run_death_test@internal@testing@@3V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@A)
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > testing::FLAGS_gtest_death_test_style" (?FLAGS_gtest_death_test_style@testing@@3V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@A)
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "class testing::internal::Mutex testing::internal::g_linked_ptr_mutex" (?g_linked_ptr_mutex@internal@testing@@3VMutex@12@A)
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "bool testing::FLAGS_gtest_also_run_disabled_tests" (?FLAGS_gtest_also_run_disabled_tests@testing@@3_NA)
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "bool testing::FLAGS_gtest_break_on_failure" (?FLAGS_gtest_break_on_failure@testing@@3_NA)
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "bool testing::FLAGS_gtest_catch_exceptions" (?FLAGS_gtest_catch_exceptions@testing@@3_NA)
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > testing::FLAGS_gtest_color" (?FLAGS_gtest_color@testing@@3V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@A)
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > testing::FLAGS_gtest_filter" (?FLAGS_gtest_filter@testing@@3V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@A)
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "bool testing::FLAGS_gtest_list_tests" (?FLAGS_gtest_list_tests@testing@@3_NA)
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > testing::FLAGS_gtest_output" (?FLAGS_gtest_output@testing@@3V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@A)
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "bool testing::FLAGS_gtest_print_time" (?FLAGS_gtest_print_time@testing@@3_NA)
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "int testing::FLAGS_gtest_random_seed" (?FLAGS_gtest_random_seed@testing@@3HA)
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "int testing::FLAGS_gtest_repeat" (?FLAGS_gtest_repeat@testing@@3HA)
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "bool testing::FLAGS_gtest_show_internal_stack_frames" (?FLAGS_gtest_show_internal_stack_frames@testing@@3_NA)
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "bool testing::FLAGS_gtest_shuffle" (?FLAGS_gtest_shuffle@testing@@3_NA)
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "int testing::FLAGS_gtest_stack_trace_depth" (?FLAGS_gtest_stack_trace_depth@testing@@3HA)
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "bool testing::FLAGS_gtest_throw_on_failure" (?FLAGS_gtest_throw_on_failure@testing@@3_NA)
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > testing::FLAGS_gtest_stream_result_to" (?FLAGS_gtest_stream_result_to@testing@@3V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@A)
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "bool testing::FLAGS_gtest_death_test_use_fork" (?FLAGS_gtest_death_test_use_fork@testing@@3_NA)
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "void const * const testing::internal::kTestTypeIdInGoogleTest" (?kTestTypeIdInGoogleTest@internal@testing@@3QBXB)
     1>gtest_unittest.obj : error LNK2001: 无法解析的外部符号 "bool testing::internal::g_help_flag" (?g_help_flag@internal@testing@@3_NA)
     1>LIBCMTD.lib(crt0.obj) : error LNK2019: 无法解析的外部符号 _main，该符号在函数 ___tmainCRTStartup 中被引用
     1>xmlconfigure/Debug\gtest_unittest.exe : fatal error LNK1120: 161 个无法解析的外部命令
     1>已完成生成项目“D:\sdk Source\xmlconfigure\googletest\msvc\gtest_unittest.vcxproj”(Build 个目标)的操作 - 失败。

生成失败。

已用时间 00:00:01.64
